# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Crown Proto' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'EstimoteSDK'
  pod 'FloatRatingView', '~> 2.0.0'
  # Pods for Crown Proto

  target 'Crown ProtoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Crown ProtoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
